Verify pull request updated time.
p2mobile/atlas-third-party-integration pull request #1
Opened 2022-03-22 23:40 UTC by nzsalt

Verify pull request updated time.
Multiple assignees.

2022-03-23 01:29 UTC, nzsalt commented
add a comment

2022-03-23 01:49 UTC, nzsalt reviewed
something is better than nothing.

2022-03-23 01:49 UTC, nzsalt commented on README.rm
> +Update 2
something else

2022-03-23 01:59 UTC, ftkghost reviewed
Done

2022-03-23 01:59 UTC, ftkghost commented on README.rm
> +Verify pull request updated time.
review from others.

2022-03-23 01:59 UTC, ftkghost commented on README.rm
> +Update 2
my comment

2022-03-23 03:01 UTC, ftkghost reviewed
test

2022-03-23 03:01 UTC, ftkghost commented on README.rm
> +Update 2
test another review

2022-03-23 03:01 UTC, ftkghost commented on README.rm
> +Update 2
to update the code

2022-03-30 22:38 UTC, ftkghost commented
this is a comment.

2022-03-30 22:45 UTC, ftkghost requested changes

2022-03-30 22:45 UTC, ftkghost commented on README.rm
> +Update 2
test a review

2022-03-30 22:49 UTC, ftkghost approved these changes

2022-03-30 22:49 UTC, merged

2022-03-30 22:49 UTC, ftkghost commented
comment after merge

2022-03-30 22:50 UTC, ftkghost commented
@nzsalt take an action